apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: eu-west-1
  tags:
    owner: ${OWNER}

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

managedNodeGroups:
- name: worker-managed-v2
  instanceType: m5.large
  desiredCapacity: 3
  minSize: 3
  maxSize: 3
  ssh:
    allow: true
  labels:
    infraNode: "true"
    workerNode: "true"
  iam:
    withAddonPolicies:
      cloudWatch: true
